sudo: required
language: generic 
services:
    - docker

before_install:
    - docker build -t justinhuang25/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true justinhuang25/docker-react npm run test -- --coverage